### ISSUE TITLE
Some typo in chapter 18, 20 & 21

### ISSUE THREAD

**Issue by guodhu** [hefengxian/my-ielts#10]
18
strik -> strike
manoeuver -> maneuver

20
beit -> bait

21
insame -> insane
hetred -> hatred
veks -> ?
remove word 3355

I have went through all the chapters and this may be the last issue created by me.
Sorry for being so picky and thank you very much for this vocabulary summary. It really helps me on the IELTS. Looking forward to your further updates.

Just curious:
How did you transcribe these words? Did you type them 1-by-1 manually? Or did you use any OCR tool?
Are these typos present on the book? Or it's introduced during the transcription?

**Comment by hefengxian** [comment]
First of all, thank you for these useful feedback. The typos you mentioned all has been fixed

- veks -> vex

> I have went through all the chapters and this may be the last issue created by me.
Sorry for being so picky and thank you very much for this vocabulary summary. It really helps me on the IELTS. Looking forward to your further updates.

I'm very grateful for the feedback you provided, which is very helpful to improve this project.

I will keep updating continuously, but considering my weak proficiency, the updates might relatively slow.

Nevertheless, I truely appreciate your attention on this project.

> Just curious:
How did you transcribe these words? Did you type them 1-by-1 manually? Or did you use any OCR tool?
Are these typos present on the book? Or it's introduced during the transcription?

All these words were typed by me one by one. This process also provided me with a good opportunity to learn them.

So, there are no error in the book. Any typos you find were caused by me.

**Comment by guodhu** [comment]
> All these words were typed by me one by one.

Amazing work!
